spring:
  security:
    oauth2:
      client:
        registration:
          github:
           scope: user
           client-id: ${GITHUB_CLIENT_ID:fb06c006c2ed62fe9e8b}
           client-secret: ${GITHUB_CLIENT_SECRET:164264e3f6d70c7c21713b7fa64225cb8d6107b2}

github:

  # Credentials are based on users belonging to a particular GitHub team,
  # by requesting the GitHub API (see github.client configuration keys).
  # This key can be found in the list of teams in your organization
  # See http://developer.github.com/v3/teams/members
  team:
    id: ${GITHUB_TEAM_ID:482984}

logging:
  level:
    org.springframework.security: DEBUG